version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    # image: ankane/pgvector
    build:
      context: .
      dockerfile: Dockerfile.pg
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  es:
    image: elasticsearch:8.9.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: kibana:8.9.2
    ports:
      - "5601:5601"
    depends_on:
      - es
    networks:
      - elastic

volumes:
  elastic-data:
    driver: local
  redis-data:
    driver: local
  db-data:
    driver: local

networks:
  elastic:
    driver: bridge